org.gradle.jvmargs=-Xmx4G
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.caching=true

version=1.16.20
group=earth.terrarium.adastra

minecraftVersion=1.21.1
parchmentVersion=2024.11.17

modMenuVersion=11.0.4
reiVersion=16.0.799
jeiVersion=19.27.0.340

# patchouliVersion=81
# shimmerVersion=0.2.3

athenaVersion=4.0.6
#cadmusVersion=1.2.0
#argonautsVersion=1.2.0

resourcefulLibVersion=3.0.12
resourcefulConfigVersion=3.0.11
cslVersion=0.0.10

neoforgeVersion=21.1.229
fabricLoaderVersion=0.19.2
fabricApiVersion=0.116.9
