org.gradle.jvmargs=-Xmx2G

enabledPlatforms=fabric,neoforge

version=1.16.6
group=earth.terrarium.adastra

minecraftVersion=1.21.1
mixinExtrasVersion=0.3.2
parchmentVersion=2024.05.01

modMenuVersion=10.0.0-beta.1
reiVersion=15.0.728
jeiVersion=17.3.0.43

patchouliVersion=81
shimmerVersion=0.2.3

athenaVersion=3.4.0
cadmusVersion=1.2.0
argonautsVersion=1.2.0

resourcefulLibVersion=2.5.5
resourcefulConfigVersion=2.5.1
botariumVersion=3.2.2